[build]
  publish = "dist/samvloeberghs-static/"
[[headers]]
  for = "*.*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31536000"
[[headers]]
  for = "*.png" # png files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.jpg" # jpg files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.svg" # svg files too
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[redirects]]
  from = "/posts/disabling-angular-when-statically-genering-with-scully"
  to = "/posts/disabling-angular-when-statically-generating-with-scully/"
